name: Update Volumes and Build Setup Image

on:
  workflow_dispatch:

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout supamanio Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Pull docker/volumes from Supabase Fork
        run: |
          # Set up a temporary directory to fetch from supabase-fork
          mkdir temp-repo
          cd temp-repo
          git init
          git remote add supabase-fork https://github.com/petronem/supabase.git
          git config core.sparseCheckout true
          echo "docker/volumes" > .git/info/sparse-checkout
          git fetch supabase-fork master
          git checkout supabase-fork/master -- docker/volumes
          cd ..
          # Move docker/volumes to volumes/ in the target repo root
          [ -d volumes ] && rm -rf volumes  # Remove existing volumes/ if it exists
          mv temp-repo/docker/volumes volumes
          rm -rf temp-repo
        shell: bash

      - name: Commit Updated Volumes
        run: |
          git add volumes/
          git commit -m "Update volumes/ from Supabase fork" || echo "No changes to commit"
          git push https://${{ secrets.PAT }}@github.com/petronem/supamanio.git main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Setup Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.setup
          push: true
          tags: petronem/supamanio-setup:latest
