name: Update Volumes and Build Setup Image

on:
  workflow_dispatch:

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout supamanio Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull docker/volumes from Supabase Fork
        run: |
          git remote add supabase-fork https://github.com/petronem/supabase.git
          git fetch supabase-fork
          if [ -d "volumes" ]; then
            git subtree pull --prefix=volumes supabase-fork master --squash
          else
            git subtree add --prefix=volumes supabase-fork master --squash
          fi
        shell: bash

      - name: Commit Updated Volumes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add volumes/
          git commit -m "Update volumes/ from Supabase fork" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Setup Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.setup
          push: true
          tags: petronem/supamanio-setup:latest
